name: PR Comment
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install requests

      - name: Run Python script
        id: run-script
        run: |
          shopt -s nullglob
          ls
          wget https://raw.githubusercontent.com/Ensign-College/CS115Lab3aTest/main/icecream_test_lab3a.py
          wget https://raw.githubusercontent.com/Ensign-College/CS115Lab3aTest/main/cookie_test_lab3a.py
          wget https://raw.githubusercontent.com/Ensign-College/CS115Lab3aTest/main/candy_test_lab3a.py
          wget https://raw.githubusercontent.com/Ensign-College/CS115Lab3aTest/main/sundae_test_lab3a.py
          wget https://raw.githubusercontent.com/Ensign-College/CS115Lab3aTest/main/dessertitem_test_lab3a.py
          files=(*.py)
          if [[ ${#files[@]} -gt 0 ]]; then
            for file in "${files[@]}"
            do
                output=$(python "$file")
                if [[ $output == *"OK"* ]]; then
                    echo "script-output::Script $file executed successfully with output: $output"
                else
                    echo "script-output::Script $file failed with output: $output"
                fi
            done
          else
            echo "No Python files found."
          fi

      - name: Comment on PR
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const issue_number = context.issue.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const script_output = "${{ steps.run-script.outputs['script-output'] }}";
            console.log('script_output: ' + script_output);
            if (script_output) {
              await github.rest.issues.createComment({
                owner: owner,
                repo: repo,
                issue_number: issue_number,
                body: script_output
              });
            }
            else {
              console.log('No script output to comment.');
            }

