name: PR Comment
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Run Python script
        id: run-script
        run: |
          shopt -s nullglob
          ls
          cd ..;
          ls
          files=(*.py)
          if [[ ${#files[@]} -gt 0 ]]; then
            for file in "${files[@]}"
            do
                output=$(python "$file")
                if [[ $output != *"OK"* ]]; then
                    echo "script-output::$output"
                fi
            done
          else
            echo "No Python files found."
          fi


      - name: Comment on PR
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const issue_number = context.issue.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const script_output = "${{ steps.run-script.outputs.script-output }}";
            await github.rest.issues.createComment({
              owner: owner,
              repo: repo,
              issue_number: issue_number,
              body: script_output
            });
